#!/usr/bin/env python3
"""Generate licensed split leakage and burst proofs. Requires Pillow; no downloads."""
import hashlib
import json
from pathlib import Path
import sys
from PIL import Image


def texture(seed):
    state = seed
    data = []
    for y in range(160):
        for x in range(192):
            state ^= (state << 13) & ((1 << 64) - 1)
            state ^= state >> 7
            state ^= (state << 17) & ((1 << 64) - 1)
            v = state % 256
            data.append((v, (x * 17 + y * 23) % 256, 255 - v))
    im = Image.new('RGB', (192, 160))
    im.putdata(data)
    return im


def generate(root):
    root.mkdir(parents=True, exist_ok=False)
    dataset, burst = root / 'dataset', root / 'burst'
    dataset.mkdir()
    burst.mkdir()
    entries, pairs = [], []
    for i, seed in enumerate([938475, 1726354]):
        original = texture(seed)
        source = f'train/source-{i}.png'
        (dataset / 'train').mkdir(exist_ok=True)
        original.save(dataset / source)
        entries.append({'path': source, 'split': 'train'})
        for transform in ['exact', 'recompressed', 'resized', 'cropped']:
            partition = 'validation' if transform in ['exact', 'recompressed'] else 'test'
            suffix = 'jpg' if transform == 'recompressed' else 'png'
            target = f'{partition}/{transform}-{i}.{suffix}'
            (dataset / partition).mkdir(exist_ok=True)
            if transform == 'exact':
                (dataset / target).write_bytes((dataset / source).read_bytes())
            elif transform == 'recompressed':
                original.save(dataset / target, quality=82, subsampling=0)
            elif transform == 'resized':
                original.resize((136, 113), Image.Resampling.BILINEAR).save(dataset / target)
            else:
                original.crop((20, 12, 164, 140)).save(dataset / target)
            entries.append({'path': target, 'split': partition})
            pairs.append({'a': source, 'b': target, 'transform': transform})
    # Independent random pixels form the held-out negative control.
    import random
    rng = random.Random(98713)
    negative = Image.frombytes('RGB', (192, 160), rng.randbytes(192 * 160 * 3))
    negative.save(dataset / 'test/unrelated.png')
    entries.append({'path': 'test/unrelated.png', 'split': 'test'})
    (dataset / 'splits.json').write_text(json.dumps({
        'schema': 'saccade-split-manifest.v1', 'entries': entries, 'injected_pairs': pairs}, indent=2)+'\n')
    shot = texture(938475)
    shot.save(burst / 'shot-0.png')
    shot.crop((1, 0, 192, 160)).save(burst / 'shot-1.png')
    shot.save(burst / 'shot-2.jpg', quality=90, subsampling=0)
    negative.save(burst / 'unrelated.png')
    (burst / 'splits.json').write_text(json.dumps({
        'schema': 'saccade-split-manifest.v1', 'entries': [
            {'path': p, 'split': 'session'} for p in ['shot-0.png', 'shot-1.png', 'shot-2.jpg', 'unrelated.png']]}, indent=2)+'\n')
    files = {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
             for p in sorted(root.rglob('*')) if p.is_file()}
    (root / 'provenance.json').write_text(json.dumps({
        'license': 'MIT OR Apache-2.0',
        'provenance': 'Procedurally generated by scripts/gen-split-fixtures.py; no external imagery.',
        'seeds': [938475, 1726354, 98713], 'sha256': files}, indent=2)+'\n')


if __name__ == '__main__':
    generate(Path(sys.argv[1]))
