from os import PathLike
from typing import Any, Sequence

Source = str | PathLike[str] | bytes
class SaccadeError(Exception):
    code: str
class InputError(SaccadeError): ...
class ModelError(SaccadeError): ...
class AnalysisError(SaccadeError): ...
class Analyzer:
    def __init__(self, profile: str = "cpu-lite", model_dir: str | None = None, allow_download: bool = False, registry: str | None = None) -> None: ...
    def analyze_media(self, source: Source, **options: Any) -> dict[str, Any]: ...
    def compare(self, a: Source, b: Source, *, ppd: float = 67.0) -> dict[str, Any]: ...
    def hash(self, source: Source) -> dict[str, int]: ...
    def embed_image(self, source: Source) -> list[float]: ...
    def embed_text(self, text: str) -> list[float]: ...
class Index:
    def __init__(self, analyzer: Analyzer) -> None: ...
    @classmethod
    def build(cls, analyzer: Analyzer, paths: Sequence[str]) -> Index: ...
    def add(self, source: Source, *, label: str = "image") -> None: ...
    def query(self, *, image: Source | None = None, text: str | None = None, top: int = 10) -> dict[str, Any]: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, analyzer: Analyzer, path: str) -> Index: ...
def model_config() -> dict[str, Any]: ...
def pull_runtime(model_dir: str | None = None) -> str: ...
def pull_models(ids: Sequence[str], model_dir: str | None = None, registry: str | None = None) -> dict[str, Any]: ...

__version__: str
def compare_maps(reference: Source, candidate: Source, tile_size: int = 32) -> dict[str, Any]: ...

def batch(source: str | PathLike[str], out: str | PathLike[str], executable: str = "saccade", options_json: str | None = None, reference_dir: str | PathLike[str] | None = None) -> list[dict[str, Any]]: ...
